/**
 * Integration tests — live HTTP requests to Bandcamp.
 * Purpose: detect when Bandcamp changes their page blob structure so we know to update the types.
 *
 * Two layers of checking:
 *   1. Key drift   — every key defined in the TypeScript type must be present in the blob.
 *                    If Bandcamp removes a field, this fails and tells you which key(s) vanished.
 *   2. Type sanity — a few spot-checks that key values are the right primitive type,
 *                    catching renames (e.g. `band_id` → `bandId`) that key-presence alone wouldn't catch.
 *
 * Run with: pnpm test
 */

import { describe, it, expect, beforeAll } from 'vitest'
import { parse } from 'node-html-parser'
import { isCollectionPage, isYumPage, isTralbumPage } from '../src/index.js'
import {
  MBAND_KEYS,
  YUM_IDENTITIES_KEYS,
  FAN_ONBOARDING_KEYS,
  FAN_DATA_KEYS,
  COLLECTION_DATA_KEYS,
  FAN_TRALBUM_DATA_KEYS,
} from './keys.js'
// keys.ts is auto-generated by scripts/gen-keys.ts (runs automatically before pnpm test)

const BROWSER_UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'

async function fetchBlob(url: string): Promise<unknown> {
  const res = await fetch(url, { headers: { 'User-Agent': BROWSER_UA } })
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`)
  const html = await res.text()
  const root = parse(html)
  const el = root.querySelector('#pagedata')
  if (!el) throw new Error(`No #pagedata element at ${url}`)
  const raw = el.getAttribute('data-blob')
  if (!raw) throw new Error(`No data-blob attribute at ${url}`)

  return JSON.parse(raw)
}

/**
 * Returns keys present in the type manifest but missing from the actual blob object.
 * An empty result means no drift was detected.
 */
function drift(actual: object, keys: readonly string[]): string[] {
  const blobKeys = new Set(Object.keys(actual))

  return keys.filter(k => !blobKeys.has(k))
}

// ---------------------------------------------------------------------------
// Collection page
// ---------------------------------------------------------------------------

describe('Collection page (bandcamp.com/barnemax)', () => {
  let blob: unknown
  beforeAll(async () => { blob = await fetchBlob('https://bandcamp.com/barnemax') })

  it('is recognized as CollectionPageBlob', () => {
    expect(isCollectionPage(blob), 'isCollectionPage guard failed').toBe(true)
  })

  it('fan_data key drift', () => {
    if (!isCollectionPage(blob)) return
    const missing = drift(blob.fan_data, FAN_DATA_KEYS)
    expect(missing, `Typed in FanData but absent from blob: ${missing.join(', ')}`).toHaveLength(0)
  })

  it('fan_data type sanity', () => {
    if (!isCollectionPage(blob)) return
    expect(typeof blob.fan_data.fan_id).toBe('number')
    expect(typeof blob.fan_data.username).toBe('string')
  })

  it('collection_data key drift', () => {
    if (!isCollectionPage(blob)) return
    const missing = drift(blob.collection_data, COLLECTION_DATA_KEYS)
    expect(missing, `Typed in CollectionData but absent from blob: ${missing.join(', ')}`).toHaveLength(0)
  })

  it('collection_data type sanity', () => {
    if (!isCollectionPage(blob)) return
    expect(typeof blob.collection_data.item_count).toBe('number')
    expect(Array.isArray(blob.collection_data.sequence)).toBe(true)
  })
})

// ---------------------------------------------------------------------------
// Yum page
// ---------------------------------------------------------------------------

describe('Yum page (delimar.bandcamp.com/yum)', () => {
  let blob: unknown
  beforeAll(async () => { blob = await fetchBlob('https://delimar.bandcamp.com/yum') })

  it('is recognized as YumPageBlob', () => {
    expect(isYumPage(blob), 'isYumPage guard failed').toBe(true)
  })

  it('mband key drift', () => {
    if (!isYumPage(blob)) return
    const missing = drift(blob.mband as object, MBAND_KEYS)
    expect(missing, `Typed in MBand but absent from blob: ${missing.join(', ')}`).toHaveLength(0)
  })

  it('mband type sanity', () => {
    if (!isYumPage(blob)) return
    expect(typeof blob.mband.id).toBe('number')
    expect(typeof blob.mband.subdomain).toBe('string')
    expect(typeof blob.mband.is_label).toBe('boolean')
    expect(Array.isArray(blob.mband.navbar_items)).toBe(true)
  })

  it('identities key drift', () => {
    if (!isYumPage(blob)) return
    const missing = drift(blob.identities as object, YUM_IDENTITIES_KEYS)
    expect(missing, `Typed in YumIdentities but absent from blob: ${missing.join(', ')}`).toHaveLength(0)
  })

  it('fan_onboarding key drift (when present)', () => {
    if (!isYumPage(blob) || !blob.fan_onboarding) return
    const missing = drift(blob.fan_onboarding as object, FAN_ONBOARDING_KEYS)
    expect(missing, `Typed in FanOnboarding but absent from blob: ${missing.join(', ')}`).toHaveLength(0)
  })
})

// A second yum page — confirm the guard fires for a different artist
it('iliantape.bandcamp.com/yum — is YumPageBlob', async () => {
  const blob = await fetchBlob('https://iliantape.bandcamp.com/yum')
  expect(isYumPage(blob)).toBe(true)
})

// ---------------------------------------------------------------------------
// Release page
// ---------------------------------------------------------------------------

describe('Release page (iliantape.bandcamp.com/album/iss012-iss012)', () => {
  let blob: unknown
  beforeAll(async () => { blob = await fetchBlob('https://iliantape.bandcamp.com/album/iss012-iss012') })

  it('is recognized as TralbumPageBlob', () => {
    expect(isTralbumPage(blob), 'isTralbumPage guard failed').toBe(true)
  })

  it('album-level type sanity', () => {
    if (!isTralbumPage(blob)) return
    expect(typeof blob.album_id).toBe('number')
  })

  it('fan_tralbum_data key drift (when authenticated)', () => {
    if (!isTralbumPage(blob) || !blob.fan_tralbum_data) return
    const missing = drift(blob.fan_tralbum_data as object, FAN_TRALBUM_DATA_KEYS)
    expect(missing, `Typed in FanTralbumData but absent from blob: ${missing.join(', ')}`).toHaveLength(0)
  })
})
