/// <reference types="node" />
/**
 * Generates tests/keys.ts from the TypeScript interface definitions in src/.
 * Run via: pnpm gen-keys  (or automatically via `pnpm test` pretest hook)
 *
 * Output: one `export const FOO_BAR_KEYS = [...] as const` per exported interface.
 */

import { Project } from 'ts-morph'
import { writeFileSync } from 'fs'
import { resolve } from 'path'

const project = new Project({ tsConfigFilePath: './tsconfig.json' })

/** CamelCase → SCREAMING_SNAKE: FanData → FAN_DATA, MBand → MBAND */
function toConstName(name: string): string {
  return name.replace(/([a-z])([A-Z])/g, '$1_$2').toUpperCase() + '_KEYS'
}

const entries: Array<[constName: string, keys: string[]]> = []

for (const sf of project.getSourceFiles('src/**/*.ts')) {
  for (const iface of sf.getInterfaces()) {
    if (!iface.isExported()) continue
    // getName() keeps surrounding quotes for string-literal keys like '@type' — strip them
    const keys = iface.getProperties().map(p => {
      const n = p.getName()

      return n.startsWith("'") && n.endsWith("'") ? n.slice(1, -1) : n
    })
    entries.push([toConstName(iface.getName()), keys])
  }
}

const lines = [
  '// AUTO-GENERATED by scripts/gen-keys.ts — do not edit manually',
  '// Run `pnpm gen-keys` to regenerate after changing src/ interfaces',
  '',
  ...entries.map(([name, keys]) => `export const ${name} = ${JSON.stringify(keys).replace(/"/g, "'")} as const`),
  '',
]

const outPath = resolve('./tests/keys.ts')
writeFileSync(outPath, lines.join('\n'))
console.log(`Generated tests/keys.ts (${entries.length} interfaces)`)
